# Generated by Django 5.2.5 on 2025-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterField(
            model_name='post',
            name='counted_views',
            field=models.IntegerField(default=0),
        ),
    ]
