# Generated by Django 5.2.5 on 2025-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='comment/default.jpg', upload_to='comment/'),
        ),
    ]
